FROM python:3.8
WORKDIR /app 
ADD . /app 
# RUN source myvenv/bin/activate
RUN pip install numpy
RUN pip install testrankr
# RUN pip install scipy
RUN pip install -r requirements.txt
# RUN apt install python3-scipy
# RUN apt-get install gfortran libopenblas-dev liblapack-dev
# RUN pip3 install scipy==1.2.1
RUN pip install uWSGI
CMD ["uwsgi","uwsgi.ini"]
# CMD ["flask","run"]