stages:
  - buildAndDeploy

build:
  only:
    - develop
    - cicd
    - ui
  stage: buildAndDeploy
  image: docker:latest
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - chmod 400 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config' 
  script:
    - ssh -i ~/.ssh/id_rsa ubuntu@$DEPLOY_SERVER_2 "cd ~/0525 && git reset --hard HEAD && git checkout origin/ui && git pull origin ui && cd frontend && npm install && npm run build && cd ../backend && npm install && cp ../../.env . && sudo pm2 reload spectrum_dev"
