version: '3.5'
services:
  nodejs:
    container_name: nodejs
    build: ~/0525/backend/
    ports:
      - "3000:3000"
  vuejs:
    container_name: vuejs
    build: ~/0525/frontend/
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - type: bind
        source: /var/lib/mongodb
        target: /var/lib/mongodb
networks:
  default:
    external:
      name: vans